### ISSUE TITLE
关于插件开发，可以给一点思路吗？

### ISSUE THREAD

**Issue by c61292558** [Wing-summer/WingHexExplorer2#10]
关于插件开发，可以给一点思路吗？
我真的一点头绪都没有，或者说你可以举一个最简单实践例子吗？
万分感谢🙏🙏🙏

**Comment by Wing-summer** [comment]
这个项目是基于我的 [WingHexExplorer](https://github.com/Wing-summer/WingHexExplorer) 重构的，插件系统虽然接口大变了一些，但是使用方式和主要核心没有变，你可以参考里面的 TestPlugin 和 BadPlugin 以及 [WingHexPy](https://github.com/Wing-summer/WingHexPy) ，还有 Gitee 上的 [WingHexDisasm](https://gitee.com/wing-cloud/wing-hex-disasm) 和 [WingHexAsm](https://gitee.com/wing-cloud/wing-hex-asm) 。

注意，插件的抢占机制已经在这个版本取消，你就当没有就行了。还有如果解决你的疑惑，你就自己主动关一下 issue，我主要是怕你还有相关疑问再问。
