### ISSUE TITLE
编译运行会出错误

### ISSUE THREAD

**Issue by c61292558** [Wing-summer/WingHexExplorer2#11]
**请描述缺陷 / Describe the bug**

请用简明的语言描述缺陷。

今天git clone一下，然后在Qt creator里面构建运行一下：
然后就提示缺了分号了：
![image](https://github.com/user-attachments/assets/7858538d-af1f-4905-b8de-816687df0036)
添加了71行这个分号之后编译再运行，
直接打开脚本编辑器，新建脚本，输入任何字符都不显示，然后再按两下直接整个程序闪退了
```
16:17:34: Starting /home/XXX/Downloads/WingHexExplorer2-1.0.0/build-WingHexExplorer2-unknown-Release/WingHexExplorer2...
qt.qpa.plugin: Could not find the Qt platform plugin "dxcb" in "/opt/deepin-shared-libs/Qt5.15.10gles/plugins/platforms"
QObject::connect: No such signal QCodeCompletionModel::changed()
QObject::connect: No such signal QCodeCompletionModel::changed()
QObject::connect: No such signal QCodeCompletionModel::changed()
completion failed
completion failed
completion failed
16:20:19: /home/XXX/Downloads/WingHexExplorer2-1.0.0/build-WingHexExplorer2-unknown-Release/WingHexExplorer2 crashed.
```

**复现方式 / To Reproduce**

请分步描述来复现这个缺陷。

**期望的正常结果 / Expected behavior**

请用简明的语言描述你预期发生什么/结果是什么？
预期应该编译没问题才对。

**截图 / Screenshots**

如果方便的话，上一个截图会更清晰地展示问题。
![image](https://github.com/user-attachments/assets/0565c1d0-3157-44f3-b2b8-9119c88757aa)

**环境 / Environment**
 - 操作系统 / OS: DeepinV23
 - 版本 / Version [e.g. QT6 v1.0.0]：5.15.10

**Comment by Wing-summer** [comment]
缺了个分号我前天发现了，最近为正增加 clang-format 支持，调整了些智能填充相关代码，现在的版本可能会有崩溃，等我在 Deepin 发布更新日志的时候看看有没有问题，到时候我的 gitaction 我肯定保证是通过的。感谢反馈。

**Comment by Wing-summer** [comment]
程序闪退已成功复现，预计下次更新会修复。

**Comment by Wing-summer** [comment]
该 Bug 已修复，等待我明晚更新，到时候我会强制推送替换掉这个 GitAction 失败的 commit，拉取的时候要注意一下。
