### ISSUE TITLE
缺乏动态库error while loading shared libraries: libicui18n.so.63

### ISSUE THREAD

**Issue by c61292558** [Wing-summer/WingHexExplorer2#8]
**请描述缺陷 / Describe the bug**

我在qt creator可以正确ctrl+r运行，但是在我选择release或者debug构建输出到文件夹之后，点击文件夹的可执行程序却提示缺乏运行库：
![image](https://github.com/user-attachments/assets/5366f262-bb8e-483f-be9e-f69e77bf1a37)
![image](https://github.com/user-attachments/assets/a0584fbd-ab03-46f0-9f8d-f711b5ce0287)

**复现方式 / To Reproduce**

请分步描述来复现这个缺陷。

Steps to reproduce the behavior count by count.

1.打开项目
2.选择release with debug information
3.打开输出文件夹中的WingHexExplorer2可执行程序
4.选择 **在终端中运行**
5.提示报错：
`/home/fgg/Downloads/WingHexExplorer2-1.0.0/build-WingHexExplorer2-unknown-RelWithDebInfo/WingHexExplorer2: error while loading shared libraries: libicui18n.so.63: cannot open shared object file: No such file or directory
`

**期望的正常结果 / Expected behavior**

请用简明的语言描述你预期发生什么/结果是什么？

**截图 / Screenshots**

如果方便的话，上一个截图会更清晰地展示问题。

**环境 / Environment**
 - 操作系统 / OS: [e.g. Win10, DeepinV23, iOS]DeepinV23
 - 版本 / Version [e.g. QT6 v1.0.0] QT CREATOR 8.0.2   QT版本5.15.10

**附加信息 / Additional context**

在这里添加一些有关问题的额外信息。

**Comment by Wing-summer** [comment]
libicui18n
ICU high-level internationalization C/C++ library
International Components for Unicode (ICU) is a set of cross-platform Unicode-
based globalization libraries with libicui18n C/C++ library providing high-
level internationalization support (formatting, collation, etc). 

这个库是用来提供跨平台的 Unicode 支持的。这应该是 QT 的依赖，我安装 Deepin 虚拟机后搜了搜确实找不到这个 DLL，你在调试模式下调用 module ，看看 libicui18n.so.63 在哪里。如果发现不在系统默认查找目录下，并且包管理没有这个包，并且你不想破坏系统的话，那就只能用个脚本 deploy 一下了。

在我使用的 KDE6 Neon 是没发现有问题的。这个项目只能保证显式用的第三方库不会因动态链接库的原因导致启动失败。但如果编译器编译进去的，那我就没辙了。

我准备在 mkinstaller/deb 下建立一个 DEPEND 类似的字典，用于创建指定操作系统平台下的 deb 安装包，因为对于这个软件定位而言，原生的包是最合适的。

如果解决了，你就把 issue 关闭掉就行了。

**Comment by c61292558** [comment]
安装了这个安装包就可以了，应该是deepin上没有这个库：http://ftp.jp.debian.org/debian/pool/main/i/icu/libicu63_63.1-6+deb10u3_amd64.deb
