### ISSUE TITLE
as脚本一定需要一个main函数作为入口吗？

### ISSUE THREAD

**Issue by c61292558** [Wing-summer/WingHexExplorer2#9]
![image](https://github.com/user-attachments/assets/256c3d6c-b00b-4d02-911f-e604caad4b47)
```
 void main(){
 	void func(int &out outputValue)
 	{
 		outputValue = 42;
 		print("hello world");
	 }
 	func();
}
```
为什么这段代码无法正常运行？

**Comment by Wing-summer** [comment]
是的，程序设计就是如此。因为 AngelScript 是需要有一个函数名作为入口来执行程序的。包括脚本控制台也是将你写的代码包装成一个函数来执行了，所以控制台使用起来还是有限制的，但我没办法实现像 python 那样的完美的脚本执行控制台。

你要把 AngelScript 当成一种 C++ 方言就行了，你就认为 AngelScript 就和 C++ 大差不差。

所以你这行代码，C++ 也不支持这么搞嵌套函数，它也不行啊。

正确的代码应该是这样的：

```as
 void func(int &out outputValue)
 {
 	outputValue = 42;
 	print("hello world");
 }

 void main(){
	int a;
 	func(a);
 	print(a);
 }
```
